kind: pipeline
type: kubernetes
name: default

clone:
  depth: 1

steps:
  - name: check
    image: docker
    commands:
      - env
    when:
      event:
        - push
        - pull_request
  - name: push
    image: plugins/ecr
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      create_repository: true
      repo: test
      registry: 682379059715.dkr.ecr.eu-central-1.amazonaws.com
      region: eu-central-1
    when:
      branch: master
      event: push
